import React, { useState, useEffect } from 'react';
import { 
  X, 
  Sparkles, 
  Volume2, 
  VolumeX, 
  Share2, 
  Check, 
  Quote, 
  Clock, 
  MapPin, 
  Music, 
  Search, 
  CreditCard, 
  Camera, 
  FileText,
  Bookmark
} from 'lucide-react';
import { generateStoryFromReceipts } from '../utils/storyGenerator';

export default function StoryReveal({ receipts, onClose }) {
  const [copied, setCopied] = useState(false);
  const [isAudioPlaying, setIsAudioPlaying] = useState(false);
  const [audioContext, setAudioContext] = useState(null);

  const story = generateStoryFromReceipts(receipts);

  // Soothing Web Audio API synthesizer ambient chord generator
  useEffect(() => {
    return () => {
      if (audioContext) {
        audioContext.close();
      }
    };
  }, [audioContext]);

  const toggleAmbience = () => {
    if (isAudioPlaying) {
      if (audioContext) {
        audioContext.close();
        setAudioContext(null);
      }
      setIsAudioPlaying(false);
    } else {
      try {
        const ctx = new (window.AudioContext || window.webkitAudioContext)();
        // Warm meditative drone chords (frequencies: 220Hz A3, 277Hz C#4, 330Hz E4)
        const freqs = [220, 277.18, 329.63];
        freqs.forEach(freq => {
          const osc = ctx.createOscillator();
          const gain = ctx.createGain();
          osc.type = 'sine';
          osc.frequency.setValueAtTime(freq, ctx.currentTime);
          gain.gain.setValueAtTime(0.04, ctx.currentTime);
          osc.connect(gain);
          gain.connect(ctx.destination);
          osc.start();
        });
        setAudioContext(ctx);
        setIsAudioPlaying(true);
      } catch (err) {
        console.error('Web Audio init failed', err);
      }
    }
  };

  const handleCopy = () => {
    const textToCopy = `${story.title}\n${story.subtitle}\n\n${story.quote}\n\n${story.takeaway}\n\n— Generated by LifeLens`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/85 backdrop-blur-xl animate-in fade-in duration-300">
      <div 
        className="relative w-full max-w-2xl max-h-[92vh] overflow-y-auto rounded-3xl bg-[#0b0e1a] border border-indigo-500/30 shadow-2xl shadow-indigo-950/70 p-6 sm:p-10"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Subtle glowing ambient backdrop */}
        <div className="absolute top-0 right-0 w-80 h-80 rounded-full bg-indigo-500/15 blur-[100px] pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-80 h-80 rounded-full bg-purple-500/15 blur-[100px] pointer-events-none" />

        {/* Header Actions */}
        <div className="flex items-center justify-between gap-4 mb-8">
          <div className="flex items-center gap-2">
            <span className="px-3 py-1 rounded-full text-xs font-mono uppercase tracking-wider bg-indigo-500/15 text-indigo-400 border border-indigo-500/30 flex items-center gap-1.5">
              <Sparkles className="w-3 h-3" />
              Story Unfolded
            </span>

            {/* Ambient Sound Toggle */}
            <button
              onClick={toggleAmbience}
              className={`flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono transition-colors border ${
                isAudioPlaying 
                  ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40' 
                  : 'bg-white/[0.05] text-slate-400 hover:text-white border-white/10'
              }`}
            >
              {isAudioPlaying ? <Volume2 className="w-3.5 h-3.5" /> : <VolumeX className="w-3.5 h-3.5" />}
              <span>{isAudioPlaying ? 'Ambient Tone On' : 'Ambient Tone'}</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="p-2 rounded-full bg-white/[0.05] hover:bg-white/[0.1] text-slate-400 hover:text-white transition-colors"
              title="Copy Story"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Share2 className="w-4 h-4" />}
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-full bg-white/[0.05] hover:bg-white/[0.1] text-slate-400 hover:text-white transition-colors"
              aria-label="Close story"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Story Title & Subtitle */}
        <div className="mb-8">
          <h2 className="text-3xl sm:text-4xl font-bold font-display text-white tracking-tight mb-2">
            {story.title}
          </h2>
          <p className="text-base sm:text-lg text-indigo-200/90 font-light">
            {story.subtitle}
          </p>
          <div className="mt-3 flex items-center gap-2 text-xs font-mono text-slate-400">
            <span>{story.dateRange}</span>
            <span>•</span>
            <span className="text-indigo-400">{story.tagline}</span>
          </div>
        </div>

        {/* Narrative Flow Progression */}
        <div className="space-y-6 mb-8 relative border-l border-indigo-500/20 pl-6 ml-3">
          {story.paragraphs.map((p, index) => (
            <div key={index} className="relative group">
              {/* Dot on timeline */}
              <div className="absolute -left-[31px] top-1.5 w-3.5 h-3.5 rounded-full bg-[#0b0e1a] border-2 border-indigo-400 flex items-center justify-center group-hover:scale-125 transition-transform">
                <div className="w-1.5 h-1.5 rounded-full bg-indigo-400" />
              </div>

              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs font-mono font-semibold text-indigo-400 uppercase tracking-wider">
                  {p.phase}
                </span>
                <span className="text-[11px] font-mono text-slate-500">
                  {p.time}
                </span>
              </div>

              <p className="text-sm sm:text-base text-slate-200 leading-relaxed font-normal">
                {p.text}
              </p>
            </div>
          ))}
        </div>

        {/* Emotional Quote Anchor */}
        {story.quote && (
          <div className="p-6 rounded-2xl bg-indigo-950/20 border border-indigo-500/30 mb-8 relative">
            <Quote className="w-8 h-8 text-indigo-400/30 absolute top-4 right-4" />
            <p className="text-base sm:text-lg italic font-serif text-indigo-100 leading-relaxed mb-3">
              "{story.quote}"
            </p>
            <p className="text-xs font-mono text-indigo-400 uppercase tracking-wider">
              {story.takeaway}
            </p>
          </div>
        )}

        {/* Bottom Connected Receipts Strip */}
        <div className="pt-6 border-t border-white/[0.08]">
          <h4 className="text-xs font-mono uppercase text-slate-400 mb-3">
            Moments that formed this story:
          </h4>
          <div className="flex flex-wrap gap-2">
            {receipts.map(r => (
              <span 
                key={r.id} 
                className="px-3 py-1.5 rounded-xl bg-white/[0.04] border border-white/[0.06] text-xs text-slate-300 font-mono flex items-center gap-1.5"
              >
                <Bookmark className="w-3 h-3 text-indigo-400" />
                <span className="truncate max-w-[140px]">{r.title}</span>
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
